import { InMemoryDbService } from 'angular-in-memory-web-api';

export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    let heroes = [
	{ id: 1, name: 'Abathur, Evolution Master', desc: 'Specialist', life: 685, regen: 1.43, AA:26, AS: 1.43, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: '/app/css/images/abathur/icon/abathur.jpg',
	  trait: 'Locust Strain', trait_img: '/app/css/images/abathur/spells/locust-strain.png',
	  Q_spell: 'Symbiote', Q_img: '/app/css/images/abathur/spells/symbiote.png',
	  W_spell: 'Toxic Nest', W_img: '/app/css/images/abathur/spells/toxic-nest.png',
	  E_spell: 0, E_img: 0,
	  R1_spell: 'Ultimate Evolution', R1_img: '/app/css/images/abathur/spells/ultimate-evolution.png',
	  R2_spell: 'Evolve Monstruosity', R2_img: '/app/css/images/abathur/spells/evolve-monstrosity.png',
	  R3_spell: 0, R3_img: 0,
	  tier1choice1: 'Pressurized Glands', tier1choice1img: '/app/css/images/abathur/talents/level1-1.png', desc1choice1: 'Increases the range of Symbiote\'s Spike Burst by 25% and decreases cooldown by 1 second', 
	  tier1choice2: 'Survival Instinct', tier1choice2img: '/app/css/images/abathur/talents/level1-2.jpg', desc1choice2: 'Increases Locust\'s Health by 50% and duration by 40%.',
	  tier1choice3: 'Regenerative Microbes', tier1choice3img: '/app/css/images/abathur/talents/level1-3.png', desc1choice3: 'Symbiote\'s Carapace heals the target for 68 Health per second over 4 seconds.',
          tier1choice4: 'Envenomed Nest', tier1choice4img: '/app/css/images/abathur/talents/level1-4.jpg', desc1choice4: 'Toxic Nests deal 75% more damage over 3 seconds.',
          tier1choice5: 0, tier1choice5img: 0, desc1choice5: 0,
	  tier2choice1: 'Prolific Dispersal', tier2choice1img: '/app/css/images/abathur/talents/level4-1.jpg', desc2choice1: 'Reduces the cooldown of Toxic Nest by 2 seconds and adds 2 additional charges.',
          tier2choice2: 'Balistospores', tier2choice2img: '/app/css/images/abathur/talents/level4-2.png', desc2choice2: 'Increases Toxic Nest\'s range to global and increases duration by 25%.',
          tier2choice3: 'Sustained Carapace', tier2choice3img: '/app/css/images/abathur/talents/level4-3.png', desc2choice3: 'Increases the Shield amount of Symbiote\'s Carapace by 40% and allows it to persist after Symbiote ends.',
          tier2choice4: 'Adrenaline Overload', tier2choice4img: '/app/css/images/abathur/talents/level4-4.jpg', desc2choice4: 'Symbiote host gains 25% increased Attack Speed.',
          tier2choice5: 0, tier2choice5img: 0, desc2choice5: 0,
	  tier3choice1: 'Needlespine', tier3choice1img: '/app/css/images/abathur/talents/level7-1.png', desc3choice1: 'Increases the damage and range of Symbiote\'s Stab by 20%.',
          tier3choice2: 'Vile Nest', tier3choice2img: '/app/css/images/abathur/talents/level7-2.jpg', desc3choice2: 'Toxic Nests slow enemy Movement Speed by 40% for 2.5 seconds.',
          tier3choice3: 'Networked Carapace', tier3choice3img: '/app/css/images/abathur/talents/level7-3.png', desc3choice3: 'Using Symbiote\'s Carapace also applies an untalented Carapace Shield to all nearby allied Heroes, Minions, and Mercenaries.',
          tier3choice4: 'Caldown: MULE', tier3choice4img: '/app/css/images/abathur/talents/level7-4.png', desc3choice4: 'Activate to calldown a Mule that repairs Structures, one at a time, near target point for 40 seconds, healing for 100 Health every 1 second. Grants 1 ammo every 3 seconds.',
          tier3choice5: 0, tier3choice5img: 0, desc3choice5: 0,
	  tier4choice1: 'Ultimate Evolution', tier4choice1img: '/app/css/images/abathur/talents/level10-1.jpg', desc4choice1: 'Clone target allied Hero and control it for 20 seconds. Abathur has perfected the clone, granting it 20% Ability Power, 20% bonus Attack Damage, and 10% bonus Movement Speed. Cannot use their Heroic Ability.',
          tier4choice2: 'Evolve Monstruosity', tier4choice2img: '/app/css/images/abathur/talents/level10-2.jpg', desc4choice2: 'Turn an allied Minion or Locust into a Monstrosity. When enemy Minions or captured Mercenaries near the Monstrosity die, it gains 5% Health and 5% Basic Attack damage, stacking up to 40 times. The Monstrosity takes 50% less damage from Minions and Structures. Using Symbiote on the Monstrosity allows you to control it, in addition to Symbiote\'s normal benefits. This ability can be reactivated to automatically cast Symbiote on your Monstrosity.',
          tier4choice3: 0, tier4choice3img: 0, desc4choice3: 0,
	  tier5choice1: 'Assault Strain', tier5choice1img: '/app/css/images/abathur/talents/level13-1.jpg', desc5choice1: 'Locust Basic Attacks cleave for 50% damage, and explode on death for 102 damage.',
          tier5choice2: 'Bombard Strain', tier5choice2img: '/app/css/images/abathur/talents/level13-2.png', desc5choice2: 'Locust\'s Basic Attacks become a long-range siege attack that deal 70% more damage.',
          tier5choice3: 'Spatial Efficiency', tier5choice3img: '/app/css/images/abathur/talents/level13-3.png', desc5choice3: 'Symbiote\'s Stab gains 1 additional charge and its Cooldown is reduced by .5 seconds. ',
          tier5choice4: 'Soma Transference', tier5choice4img: '/app/css/images/abathur/talents/level13-4.png', desc5choice4: 'Symbiote\'s Spike Burst heals the host for 64 Health per enemy Hero hit.',
          tier5choice5: 0, tier5choice5img: 0, desc5choice5: 0,
	  tier6choice1: 'Envenomed Spikes', tier6choice1img: '/app/css/images/abathur/talents/level16-1.png', desc6choice1: 'Your Symbiote\'s Spike Burst also slows enemy Movement Speed by 40% for 2 seconds.',
          tier6choice2: 'Adrenaline Boost', tier6choice2img: '/app/css/images/abathur/talents/level16-2.png', desc6choice2: 'Symbiote\'s Carapace increases the Movement Speed of the target by 40% for 3.5 seconds.',
          tier6choice3: 'Locust Brood', tier6choice3img: '/app/css/images/abathur/talents/level16-3.jpg', desc6choice3: 'Activate to spawn 3 Locusts at a nearby location.',
          tier6choice4: 'Volatile Mutation', tier6choice4img: '/app/css/images/abathur/talents/level16-4.png', desc6choice4: 'Ultimate Evolution clones and Monstrosities deal 137 damage to nearby enemies every 3 seconds and when they die.',
          tier6choice5: 0, tier6choice5img: 0, desc6choice5: 0,
	  tier7choice1: 'Evolutionary Link', tier7choice1img: '/app/css/images/abathur/talents/level20-1.jpg', desc7choice1: 'As long as the Ultimate Evolution is alive, the original target of the clone gains a Shield equal to 25% of their maximum Health. Refreshes every 5 seconds.',
          tier7choice2: 'Evolution Complete', tier7choice2img: '/app/css/images/abathur/talents/level20-2.jpg', desc7choice2: 'Monstrosity gains the ability to Deep Tunnel to any visible location once every 25 seconds.',
          tier7choice3: 'Hivemind', tier7choice3img: '/app/css/images/abathur/talents/level20-3.jpg', desc7choice3: 'Symbiote creates an additional Symbiote on a nearby allied Hero. This Symbiote mimics the commands of the first, but does half damage and shielding.',
          tier7choice4: 'Locust Nest', tier7choice4img: '/app/css/images/abathur/talents/level20-4.png', desc7choice4: 'Activate to create a nest that periodically spawns Locusts. Only one Locust Nest can be active at a time.',
          tier7choice5: 0, tier7choice5img: 0, desc7choice5: 0 },
        { id: 2, name: 'Alarak, Highlord of the Taldarim', desc: 'Assassin', life: 1900, regen: 3.96, AA:140, AS: 1.2, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/alarak/skins/thumbnails/highlord-of-the-taldarim.jpg',
  	  trait: 'Sadism', trait_img: 'http://media.blizzard.com/heroes/alarak/abilities/icons/sadism.png',
  	  Q_spell: 'Discord Strike', Q_img: 'http://media.blizzard.com/heroes/alarak/abilities/icons/discord-strike.png',
  	  W_spell: 'Telekinesis', W_img: 'http://media.blizzard.com/heroes/alarak/abilities/icons/telekinesis.png',
  	  E_spell: 'Lightning Surge', E_img: 'http://media.blizzard.com/heroes/alarak/abilities/icons/lightning-surge.png',
  	  R1_spell: 'Deadly Charge', R1_img: 'http://media.blizzard.com/heroes/alarak/abilities/icons/deadly-charge.png',
  	  R2_spell: 'Counter Strike', R2_img: 'http://media.blizzard.com/heroes/alarak/abilities/icons/counter-strike.png',
	  R3_spell: 0, R3_img: 0},
        { id: 3, name: 'Anub\'arak, Traitor King', desc: 'Warrior', life: 2003, regen: 4.17, AA:99, AS: 1.0, armor: 0, Parmor: 0, Marmor: 20, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/anubarak/skins/thumbnails/traitor-king.jpg',
          trait: 'Scarab Host', trait_img: 'http://media.blizzard.com/heroes/anubarak/abilities/icons/scarab-host.png',
          Q_spell: 'Impale', Q_img: 'http://media.blizzard.com/heroes/anubarak/abilities/icons/impale.png',
          W_spell: 'Harden Carapace', W_img: 'http://media.blizzard.com/heroes/anubarak/abilities/icons/harden-carapace.png',
          E_spell: 'Burrow Charge', E_img: 'http://media.blizzard.com/heroes/anubarak/abilities/icons/burrow-charge.png',
          R1_spell: 'Locust Swarm', R1_img: 'http://media.blizzard.com/heroes/anubarak/abilities/icons/locust-swarm.png',
          R2_spell: 'Cocoon', R2_img: 'http://media.blizzard.com/heroes/anubarak/abilities/icons/cocoon.png',
	  R3_spell: 0, R3_img: 0},
        { id: 4, name: 'Artanis, Hierarch of the Daelaam', desc: 'Warrior', life: 2470, regen: 5.14, AA:111, AS: 1.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/artanis/skins/thumbnails/hierarch-of-the-daelaam.jpg',
          trait: 'Shield Overload', trait_img: 'http://media.blizzard.com/heroes/artanis/abilities/icons/shield-overload.png',
          Q_spell: 'Blade Dash', Q_img: 'http://media.blizzard.com/heroes/artanis/abilities/icons/blade-dash.png',
          W_spell: 'Twin Blades', W_img: 'http://media.blizzard.com/heroes/artanis/abilities/icons/twin-blades.png',
          E_spell: 'Phase Prism', E_img: 'http://media.blizzard.com/heroes/artanis/abilities/icons/phase-prism.png',
          R1_spell: 'Suppression Pulse', R1_img: 'http://media.blizzard.com/heroes/artanis/abilities/icons/suppression-pulse.png',
          R2_spell: 'Purifier Beam', R2_img: 'http://media.blizzard.com/heroes/artanis/abilities/icons/purifier-beam.png',
	  R3_spell: 0, R3_img: 0},
        { id: 5, name: 'Arthas, the Lich King', desc: 'Warrior', life: 2524, regen: 5.26, AA:95, AS: 1.0, armor: 0, Parmor: 10, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/arthas/skins/thumbnails/the-lich-king.jpg',
          trait: 'Frostmourne Hungers', trait_img: 'http://media.blizzard.com/heroes/arthas/abilities/icons/frostmourne-hungers.png',
          Q_spell: 'Death Coil', Q_img: 'http://media.blizzard.com/heroes/arthas/abilities/icons/death-coil.png',
          W_spell: 'Howling Blast', W_img: 'http://media.blizzard.com/heroes/arthas/abilities/icons/howling-blast.png',
          E_spell: 'Frozen Tempest', E_img: 'http://media.blizzard.com/heroes/arthas/abilities/icons/frozen-tempest.png',
          R1_spell: 'Army of the Dead', R1_img: 'http://media.blizzard.com/heroes/arthas/abilities/icons/army-of-the-dead.png',
          R2_spell: 'Summon Sindragosa', R2_img: 'http://media.blizzard.com/heroes/arthas/abilities/icons/summon-sindragosa.png',
	  R3_spell: 0, R3_img: 0},
        { id: 6, name: 'Auriel, Archangel of Hope', desc: 'Support', life: 1850, regen: 3.85, AA:60, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/auriel/skins/thumbnails/archangel-of-hope.jpg',
          trait: 'Bestow Hope', trait_img: 'http://media.blizzard.com/heroes/auriel/abilities/icons/bestow-hope.png',
          Q_spell: 'Sacred Sweep', Q_img: 'http://media.blizzard.com/heroes/auriel/abilities/icons/sacred-sweep.png',
          W_spell: 'Ray of Heaven', W_img: 'http://media.blizzard.com/heroes/auriel/abilities/icons/ray-of-heaven.png',
          E_spell: 'Detainment Strike', E_img: 'http://media.blizzard.com/heroes/auriel/abilities/icons/detainment-strike.png',
          R1_spell: 'Resurrect', R1_img: 'http://media.blizzard.com/heroes/auriel/abilities/icons/resurrect.png',
          R2_spell: 'Crystal Aegis', R2_img: 'http://media.blizzard.com/heroes/auriel/abilities/icons/crystal-aegis.png',
	  R3_spell: 0, R3_img: 0},
        { id: 7, name: 'Azmodan, Lord of Sin', desc: 'Specialist', life: 2738, regen: 5.70, AA:85, AS: 1.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/azmodan/skins/thumbnails/lord-of-sin.jpg',
          trait: 'General of Hell', trait_img: 'http://media.blizzard.com/heroes/azmodan/abilities/icons/general-of-hell.png',
          Q_spell: 'Globe of Annihilation', Q_img: 'http://media.blizzard.com/heroes/azmodan/abilities/icons/globe-of-annihilation.png',
          W_spell: 'Summon Demon Warrior', W_img: 'http://media.blizzard.com/heroes/azmodan/abilities/icons/summon-demon-warrior.png',
          E_spell: 'All Shall Burn', E_img: 'http://media.blizzard.com/heroes/azmodan/abilities/icons/all-shall-burn.png',
          R1_spell: 'Demonic Invasion', R1_img: 'http://media.blizzard.com/heroes/azmodan/abilities/icons/demonic-invasion.png',
          R2_spell: 'Black Pool', R2_img: 'http://media.blizzard.com/heroes/azmodan/abilities/icons/black-pool.png',
	  R3_spell: 0, R3_img: 0},
        { id: 8, name: 'Brightwing, Faerie Dragon', desc: 'Support', life: 1470, regen: 3.06, AA:85, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/brightwing/skins/thumbnails/faerie-dragon.jpg',
          trait: 'Soothing Mist', trait_img: 'http://media.blizzard.com/heroes/brightwing/abilities/icons/soothing-mist.png',
          Q_spell: 'Arcane Flare', Q_img: 'http://media.blizzard.com/heroes/brightwing/abilities/icons/arcane-flare.png',
          W_spell: 'Polymorph', W_img: 'http://media.blizzard.com/heroes/brightwing/abilities/icons/polymorph.png',
          E_spell: 'Pixie Dust', E_img: 'http://media.blizzard.com/heroes/brightwing/abilities/icons/pixie-dust.png',
          R1_spell: 'Blink Heal', R1_img: 'http://media.blizzard.com/heroes/brightwing/abilities/icons/blink-heal.png',
          R2_spell: 'Emerald Wind', R2_img: 'http://media.blizzard.com/heroes/brightwing/abilities/icons/emerald-wind.png',
	  R3_spell: 0, R3_img: 0},
        { id: 9, name: 'Cassia, Amazon Warmatron', desc: 'Assassin', life: 1660, regen: 4.0, AA:125, AS: 1.33, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/cassia/skins/thumbnails/amazon-warmatron.jpg',
          trait: 'Avoidance', trait_img: 'http://media.blizzard.com/heroes/cassia/abilities/icons/avoidance.png',
          Q_spell: 'Lightning Fury', Q_img: 'http://media.blizzard.com/heroes/cassia/abilities/icons/lightning-fury.png',
          W_spell: 'Blinding Light', W_img: 'http://media.blizzard.com/heroes/cassia/abilities/icons/blinding-light.png',
          E_spell: 'Fend', E_img: 'http://media.blizzard.com/heroes/cassia/abilities/icons/fend.png',
          R1_spell: 'Ball Lightning', R1_img: 'http://media.blizzard.com/heroes/cassia/abilities/icons/ball-lightning.png',
          R2_spell: 'Valkyrie', R2_img: 'http://media.blizzard.com/heroes/cassia/abilities/icons/valkyrie.png',
	  R3_spell: 0, R3_img: 0},
	{ id: 10, name: 'Chen, Legendary Brewmaster', desc: 'Warrior', life: 2550, regen: 5.31, AA:94, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/chen/skins/thumbnails/legendary-brewmaster.jpg',
          trait: 'Fortifying Brew', trait_img: 'http://media.blizzard.com/heroes/chen/abilities/icons/fortifying-brew.png',
          Q_spell: 'Flying Kick', Q_img: 'http://media.blizzard.com/heroes/chen/abilities/icons/flying-kick.png',
          W_spell: 'Keg Smash', W_img: 'http://media.blizzard.com/heroes/chen/abilities/icons/keg-smash.png',
          E_spell: 'Breath of Fire', E_img: 'http://media.blizzard.com/heroes/chen/abilities/icons/breath-of-fire.png',
          R1_spell: 'Wandering Keg', R1_img: 'http://media.blizzard.com/heroes/chen/abilities/icons/wandering-keg.png',
          R2_spell: 'Storm, Earth, Fire', R2_img: 'http://media.blizzard.com/heroes/chen/abilities/icons/storm-earth-fire.png',
	  R3_spell: 0, R3_img: 0},
        { id: 11, name: 'Cho, Twilights Hammer Chieftain', desc: 'Warrior', life: 2950, regen: 6.15, AA:130, AS: 0.91, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/chogall/skins/thumbnails/cho/twilights-hammer-chieftain.jpg',
          trait: 'Ogre Hide', trait_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/cho/ogre-hide.png',
          Q_spell: 'Surging Fist', Q_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/cho/surging-fist.png',
          W_spell: 'Consuming Blaze', W_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/cho/consuming-blaze.png',
          E_spell: 'Rune Bomb', E_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/cho/rune-bomb.png',
          R1_spell: 'Hammer of Twilight', R1_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/cho/hammer-of-twilight.png',
          R2_spell: 'Upheaval', R2_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/cho/upheaval.png',
	  R3_spell: 0, R3_img: 0},
        { id: 12, name: 'Chromie, Keeper of Time', desc: 'Assassin', life: 1323, regen: 2.76, AA:73, AS: 1.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/chromie/skins/thumbnails/keeper-of-time.jpg',
          trait: 'Timewalker', trait_img: 'http://media.blizzard.com/heroes/chromie/abilities/icons/timewalker.png',
          Q_spell: 'Sand Blast', Q_img: 'http://media.blizzard.com/heroes/chromie/abilities/icons/sand-blast.png',
          W_spell: 'Dragon\'s Breath', W_img: 'http://media.blizzard.com/heroes/chromie/abilities/icons/dragons-breath.png',
          E_spell: 'Time Trap', E_img: 'http://media.blizzard.com/heroes/chromie/abilities/icons/time-trap.png',
          R1_spell: 'Slowing Sands', R1_img: 'http://media.blizzard.com/heroes/chromie/abilities/icons/slowing-sands.png',
          R2_spell: 'Temporal Loop', R2_img: 'http://media.blizzard.com/heroes/chromie/abilities/icons/temporal-loop.png',
	  R3_spell: 0, R3_img: 0},
        { id: 13, name: 'D.va, Meka Pilot', desc: 'Warrior', life: 0, regen: 0, AA:0, AS: 0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/dva/skins/thumbnails/meka-pilot.jpg',
          trait: 'Mech mode', trait_img: 'http://media.blizzard.com/heroes/dva/abilities/icons/mech-mode.png',
          Q_spell: 'Boosters', Q_img: 'http://media.blizzard.com/heroes/dva/abilities/icons/boosters.png',
          W_spell: 'Defense Matrix', W_img: 'http://media.blizzard.com/heroes/dva/abilities/icons/defense-matrix.png',
          E_spell: 'Self-Destruct', E_img: 'http://media.blizzard.com/heroes/dva/abilities/icons/self-destruct.png',
          R1_spell: 'Bunny Hop', R1_img: 'http://media.blizzard.com/heroes/dva/abilities/icons/bunny-hop.png',
          R2_spell: 'Big Shot', R2_img: 'http://media.blizzard.com/heroes/dva/abilities/icons/big-shot.png',
	  R3_spell: 0, R3_img: 0},
        { id: 14, name: 'Dehaka, Primal Pack Leader', desc: 'Warrior', life: 2434, regen: 5.07, AA:110, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/dehaka/skins/thumbnails/primal-pack-leader.jpg',
          trait: 'Essence Collection', trait_img: 'http://media.blizzard.com/heroes/dehaka/abilities/icons/essence-collection.png',
          Q_spell: 'Drag', Q_img: 'http://media.blizzard.com/heroes/dehaka/abilities/icons/drag.png',
          W_spell: 'Dark Swarm', W_img: 'http://media.blizzard.com/heroes/dehaka/abilities/icons/dark-swarm.png',
          E_spell: 'Burrow', E_img: 'http://media.blizzard.com/heroes/dehaka/abilities/icons/burrow.png',
          R1_spell: 'Isolation', R1_img: 'http://media.blizzard.com/heroes/dehaka/abilities/icons/isolation.png',
          R2_spell: 'Adaptation', R2_img: 'http://media.blizzard.com/heroes/dehaka/abilities/icons/adaptation.png',
	  R3_spell: 0, R3_img: 0},
        { id: 15, name: 'Diablo, Lord of Terror', desc: 'Warrior', life: 2567, regen: 5.35, AA:118, AS: 0.91, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/diablo/skins/thumbnails/lord-of-terror.jpg',
          trait: 'Black Soulstone', trait_img: 'http://media.blizzard.com/heroes/diablo/abilities/icons/black-soulstone.png',
          Q_spell: 'Shadow Charge', Q_img: 'http://media.blizzard.com/heroes/diablo/abilities/icons/shadow-charge.png',
          W_spell: 'Fire Stomp', W_img: 'http://media.blizzard.com/heroes/diablo/abilities/icons/fire-stomp.png',
          E_spell: 'Overpower', E_img: 'http://media.blizzard.com/heroes/diablo/abilities/icons/overpower.png',
          R1_spell: 'Apocalypse', R1_img: 'http://media.blizzard.com/heroes/diablo/abilities/icons/apocalypse.png',
          R2_spell: 'Lightning Breath', R2_img: 'http://media.blizzard.com/heroes/diablo/abilities/icons/lightning-breath.png',
	  R3_spell: 0, R3_img: 0},
        { id: 16, name: 'E.T.C, Rock God', desc: 'Warrior', life: 2180, regen: 4.543, AA:99, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/etc/skins/thumbnails/rock-god.jpg',
          trait: 'Rockstar', trait_img: 'http://media.blizzard.com/heroes/etc/abilities/icons/rockstar.png',
          Q_spell: 'Powerslide', Q_img: 'http://media.blizzard.com/heroes/etc/abilities/icons/powerslide.png',
          W_spell: 'Face Melt', W_img: 'http://media.blizzard.com/heroes/etc/abilities/icons/face-melt.png',
          E_spell: 'Guitar Solo', E_img: 'http://media.blizzard.com/heroes/etc/abilities/icons/guitar-solo.png',
          R1_spell: 'Mosh Pit', R1_img: 'http://media.blizzard.com/heroes/etc/abilities/icons/mosh-pit.png',
          R2_spell: 'Stage Dive', R2_img: 'http://media.blizzard.com/heroes/etc/abilities/icons/stage-dive.png',
	  R3_spell: 0, R3_img: 0},
        { id: 17, name: 'Falstad, Wildhammer Thane', desc: 'Assassin', life: 1365, regen: 2.84, AA:104, AS: 1.43, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/falstad/skins/thumbnails/wildhammer-thane.jpg',
          trait: 'Tailwing', trait_img: 'http://media.blizzard.com/heroes/falstad/abilities/icons/tailwing.png',
          Q_spell: 'Hammerang', Q_img: 'http://media.blizzard.com/heroes/falstad/abilities/icons/hammerang.png',
          W_spell: 'Lightning Rod', W_img: 'http://media.blizzard.com/heroes/falstad/abilities/icons/lightning-rod.png',
          E_spell: 'Barrel Roll', E_img: 'http://media.blizzard.com/heroes/falstad/abilities/icons/barrel-roll.png',
          R1_spell: 'Hinterland Blast', R1_img: 'http://media.blizzard.com/heroes/falstad/abilities/icons/hinterland-blast.png',
          R2_spell: 'Mighty Gust', R2_img: 'http://media.blizzard.com/heroes/falstad/abilities/icons/mighty-gust.png',
	  R3_spell: 0, R3_img: 0},
        { id: 18, name: 'Gall, Twilight Hammer Chieftain', desc: 'Assassin', life: 0, regen: 0, AA:0, AS: 0, armor: 0, Parmor: 0, Marmor: 0, scale: 5.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/chogall/skins/thumbnails/gall/twilights-hammer-chieftain.jpg',
          trait: 'Ogre Rage', trait_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/gall/ogre-rage.png',
          Q_spell: 'Shadowflame', Q_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/gall/shadowflame.png',
          W_spell: 'Dread Orb', W_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/gall/dread-orb.png',
          E_spell: 'Runic Blast', E_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/gall/runic-blast.png',
          R1_spell: 'Shadow Bolt Volley', R1_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/gall/shadow-bolt-volley.png',
          R2_spell: 'Twisting Nether', R2_img: 'http://media.blizzard.com/heroes/chogall/abilities/icons/gall/twisting-nether.png',
	  R3_spell: 0, R3_img: 0},
	{ id: 19, name: 'Gazlowe, Boss of Ratchet', desc: 'Specialist', life: 1826, regen: 3.80, AA:95, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/gazlowe/skins/thumbnails/boss-of-ratchet.jpg',
          trait: 'Salvager', trait_img: 'http://media.blizzard.com/heroes/gazlowe/abilities/icons/salvager.png',
          Q_spell: 'Rock-it! Turret', Q_img: 'http://media.blizzard.com/heroes/gazlowe/abilities/icons/rock-it-turret.png',
          W_spell: 'Deth Lazor', W_img: 'http://media.blizzard.com/heroes/gazlowe/abilities/icons/deth-lazor.png',
          E_spell: 'Xplodium Charge', E_img: 'http://media.blizzard.com/heroes/gazlowe/abilities/icons/xplodium-charge.png',
          R1_spell: 'Robo-Goblin', R1_img: 'http://media.blizzard.com/heroes/gazlowe/abilities/icons/robo-goblin.png',
          R2_spell: 'Grav-O Bomb 3000', R2_img: 'http://media.blizzard.com/heroes/gazlowe/abilities/icons/grav-o-bomb-3000.png',
	  R3_spell: 0, R3_img: 0},
        { id: 20, name: 'Genji, Cybernetic Ninja', desc: 'Assassin', life: 0, regen: 0, AA:0, AS: 0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/genji/skins/thumbnails/cybernetic-ninja.jpg',
          trait: 'Cyber Agility', trait_img: 'http://media.blizzard.com/heroes/genji/abilities/icons/cyber-agility.png',
          Q_spell: 'Shuriken', Q_img: 'http://media.blizzard.com/heroes/genji/abilities/icons/shuriken.png',
          W_spell: 'Deflect', W_img: 'http://media.blizzard.com/heroes/genji/abilities/icons/deflect.png',
          E_spell: 'Swift Strike', E_img: 'http://media.blizzard.com/heroes/genji/abilities/icons/swift-strike.png',
          R1_spell: 'Dragonbalde', R1_img: 'http://media.blizzard.com/heroes/genji/abilities/icons/dragonblade.png',
          R2_spell: 'X-strike', R2_img: 'http://media.blizzard.com/heroes/genji/abilities/icons/x-strike.png',
	  R3_spell: 0, R3_img: 0},
        { id: 21, name: 'Greymane, Lord of the Worgen', desc: 'Assassin', life: 1876, regen: 3.91, AA:140, AS: 1.0, armor: 0, Parmor: 0, Marmor: 0, scale: 0, scaleA: 4.0, scaleH: 4.5,
	  icone_img: 'http://media.blizzard.com/heroes/greymane/skins/thumbnails/greymane/lord-of-the-worgen.jpg',
          trait: 'Curse of the Worgen', trait_img: 'http://media.blizzard.com/heroes/greymane/abilities/icons/greymane/curse-of-the-worgen.png',
          Q_spell: 'Gilnean Cocktail', Q_img: 'http://media.blizzard.com/heroes/greymane/abilities/icons/greymane/gilnean-cocktail.png',
          W_spell: 'Inner Beast', W_img: 'http://media.blizzard.com/heroes/greymane/abilities/icons/greymane/inner-beast.png',
          E_spell: 'Darkflight', E_img: 'http://media.blizzard.com/heroes/greymane/abilities/icons/greymane/darkflight.png',
          R1_spell: 'Go for the Throat', R1_img: 'http://media.blizzard.com/heroes/greymane/abilities/icons/greymane/go-for-the-throat.png',
          R2_spell: 'Cursed Bullet', R2_img: 'http://media.blizzard.com/heroes/greymane/abilities/icons/greymane/cursed-bullet.png',
	  R3_spell: 0, R3_img: 0},
        { id: 22, name: 'Gul\'dan, Darkness Incarnate', desc: 'Assassin', life: 1700, regen: 3.54, AA:60, AS: 1.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/guldan/skins/thumbnails/darkness-incarnate.jpg',
          trait: 'Life Tap', trait_img: 'http://media.blizzard.com/heroes/guldan/abilities/icons/life-tap.png',
          Q_spell: 'Fel Flame', Q_img: 'http://media.blizzard.com/heroes/guldan/abilities/icons/fel-flame.png',
          W_spell: 'Drain Life', W_img: 'http://media.blizzard.com/heroes/guldan/abilities/icons/drain-life.png',
          E_spell: 'Corruption', E_img: 'http://media.blizzard.com/heroes/guldan/abilities/icons/corruption.png',
          R1_spell: 'Horrify', R1_img: 'http://media.blizzard.com/heroes/guldan/abilities/icons/horrify.png',
          R2_spell: 'Rain of Destruction', R2_img: 'http://media.blizzard.com/heroes/guldan/abilities/icons/rain-of-destruction.png',
	  R3_spell: 0, R3_img: 0},
        { id: 23, name: 'Illidan, the Betrayer', desc: 'Assassin', life: 1650, regen: 3.44, AA:78, AS: 1.82, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/illidan/skins/thumbnails/the-betrayer.jpg',
          trait: 'Betrayer\'s Thirst', trait_img: 'http://media.blizzard.com/heroes/illidan/abilities/icons/betrayers-thirst.png',
          Q_spell: 'Dive', Q_img: 'http://media.blizzard.com/heroes/illidan/abilities/icons/dive.png',
          W_spell: 'Sweeping Strike', W_img: 'http://media.blizzard.com/heroes/illidan/abilities/icons/sweeping-strike.png',
          E_spell: 'Evasion', E_img: 'http://media.blizzard.com/heroes/illidan/abilities/icons/evasion.png',
          R1_spell: 'Metamorphosis', R1_img: 'http://media.blizzard.com/heroes/illidan/abilities/icons/metamorphosis.png',
          R2_spell: 'The Hunt', R2_img: 'http://media.blizzard.com/heroes/illidan/abilities/icons/the-hunt.png',
	  R3_spell: 0, R3_img: 0},
        { id: 24, name: 'Jaina, Archmage', desc: 'Assassin', life: 1365, regen: 2.84, AA:60, AS: 1.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/jaina/skins/thumbnails/archmage.jpg',
          trait: 'Frostbite', trait_img: 'http://media.blizzard.com/heroes/jaina/abilities/icons/frostbite.png',
          Q_spell: 'Frostbolt', Q_img: 'http://media.blizzard.com/heroes/jaina/abilities/icons/frostbolt.png',
          W_spell: 'Blizzard', W_img: 'http://media.blizzard.com/heroes/jaina/abilities/icons/blizzard.png',
          E_spell: 'Cone of Cold', E_img: 'http://media.blizzard.com/heroes/jaina/abilities/icons/cone-of-cold.png',
          R1_spell: 'Ring of Frost', R1_img: 'http://media.blizzard.com/heroes/jaina/abilities/icons/ring-of-frost.png',
          R2_spell: 'Summon Water Elemental', R2_img: 'http://media.blizzard.com/heroes/jaina/abilities/icons/summon-water-elemental.png',
	  R3_spell: 0, R3_img: 0},
        { id: 25, name: 'Johanna, Crusader of Zakarum', desc: 'Warrior', life: 2179, regen: 4.54, AA:99, AS: 0.91, armor: 0, Parmor: 25, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/johanna/skins/thumbnails/crusader-of-zakarum.jpg',
          trait: 'Iron Skin', trait_img: 'http://media.blizzard.com/heroes/johanna/abilities/icons/iron-skin.png',
          Q_spell: 'Punish', Q_img: 'http://media.blizzard.com/heroes/johanna/abilities/icons/punish.png',
          W_spell: 'Condemn', W_img: 'http://media.blizzard.com/heroes/johanna/abilities/icons/condemn.png',
          E_spell: 'Shield Glare', E_img: 'http://media.blizzard.com/heroes/johanna/abilities/icons/shield-glare.png',
          R1_spell: 'Falling Sword', R1_img: 'http://media.blizzard.com/heroes/johanna/abilities/icons/falling-sword.png',
          R2_spell: 'Blessed Shield', R2_img: 'http://media.blizzard.com/heroes/johanna/abilities/icons/blessed-shield.png',
	  R3_spell: 0, R3_img: 0},
        { id: 26, name: 'Kael\'thas, the Sun King', desc: 'Assassin', life: 1520, regen: 3.17, AA:65, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/kaelthas/skins/thumbnails/the-sun-king.jpg',
          trait: 'Verdant Spheres', trait_img: 'http://media.blizzard.com/heroes/kaelthas/abilities/icons/verdant-spheres.png',
          Q_spell: 'Flamestrike', Q_img: 'http://media.blizzard.com/heroes/kaelthas/abilities/icons/flamestrike.png',
          W_spell: 'Living Bomb', W_img: 'http://media.blizzard.com/heroes/kaelthas/abilities/icons/living-bomb.png',
          E_spell: 'Gravity Lapse', E_img: 'http://media.blizzard.com/heroes/kaelthas/abilities/icons/gravity-lapse.png',
          R1_spell: 'Phoenix', R1_img: 'http://media.blizzard.com/heroes/kaelthas/abilities/icons/phoenix.png',
          R2_spell: 'Pyroblast', R2_img: 'http://media.blizzard.com/heroes/kaelthas/abilities/icons/pyroblast.png',
	  R3_spell: 0, R3_img: 0},
        { id: 27, name: 'Kerrigan, Queen of Blades', desc: 'Assassin', life: 1680, regen: 3.50, AA:120, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/kerrigan/skins/thumbnails/queen-of-blades.jpg',
          trait: 'Assimilation', trait_img: 'http://media.blizzard.com/heroes/kerrigan/abilities/icons/assimilation.png',
          Q_spell: 'Ravage', Q_img: 'http://media.blizzard.com/heroes/kerrigan/abilities/icons/ravage.png',
          W_spell: 'Impaling Blades', W_img: 'http://media.blizzard.com/heroes/kerrigan/abilities/icons/impaling-blades.png',
          E_spell: 'Primal Grasp', E_img: 'http://media.blizzard.com/heroes/kerrigan/abilities/icons/primal-grasp.png',
          R1_spell: 'Maelstom', R1_img: 'http://media.blizzard.com/heroes/kerrigan/abilities/icons/maelstrom.png',
          R2_spell: 'Summon Ultralisk', R2_img: 'http://media.blizzard.com/heroes/kerrigan/abilities/icons/summon-ultralisk.png',
	  R3_spell: 0, R3_img: 0},
	{ id: 28, name: 'Kharazim, Veradani monk', desc: 'Support', life: 1949, regen: 4.06, AA:63, AS: 2.00, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/kharazim/skins/thumbnails/veradani-monk.jpg',
          trait: 'Pick your Trait', trait_img: 'http://media.blizzard.com/heroes/kharazim/abilities/icons/pick-your-trait.png',
          Q_spell: 'Radiant Dash', Q_img: 'http://media.blizzard.com/heroes/kharazim/abilities/icons/radiant-dash.png',
          W_spell: 'Breath of Heaven', W_img: 'http://media.blizzard.com/heroes/kharazim/abilities/icons/breath-of-heaven.png',
          E_spell: 'Deadly Reach', E_img: 'http://media.blizzard.com/heroes/kharazim/abilities/icons/deadly-reach.png',
          R1_spell: 'Divine Palm', R1_img: 'http://media.blizzard.com/heroes/kharazim/abilities/icons/divine-palm.png',
          R2_spell: 'Seven-Sided Strike', R2_img: 'http://media.blizzard.com/heroes/kharazim/abilities/icons/seven-sided-strike.png',
	  R3_spell: 0, R3_img: 0},
        { id: 29, name: 'Leoric, the Skeleton King', desc: 'Warrior', life: 2468, regen: 5.14, AA:150, AS: 0.77, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/leoric/skins/thumbnails/the-skeleton-king.jpg',
          trait: 'Undying', trait_img: 'http://media.blizzard.com/heroes/leoric/abilities/icons/undying.png',
          Q_spell: 'Skeletal Swing', Q_img: 'http://media.blizzard.com/heroes/leoric/abilities/icons/skeletal-swing.png',
          W_spell: 'Drain Hope', W_img: 'http://media.blizzard.com/heroes/leoric/abilities/icons/drain-hope.png',
          E_spell: 'Wraith Walk', E_img: 'http://media.blizzard.com/heroes/leoric/abilities/icons/wraith-walk.png',
          R1_spell: 'Entomb', R1_img: 'http://media.blizzard.com/heroes/leoric/abilities/icons/entomb.png',
          R2_spell: 'March of the Black King', R2_img: 'http://media.blizzard.com/heroes/leoric/abilities/icons/march-of-the-black-king.png',
	  R3_spell: 0, R3_img: 0},
        { id: 30, name: 'Lili, World Wanderer', desc: 'Support', life: 1552, regen: 3.23, AA:63, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/li-li/skins/thumbnails/world-wanderer.jpg',
          trait: 'Fast Feet', trait_img: 'http://media.blizzard.com/heroes/li-li/abilities/icons/fast-feet.png',
          Q_spell: 'Healing Brew', Q_img: 'http://media.blizzard.com/heroes/li-li/abilities/icons/healing-brew.png',
          W_spell: 'Cloud Serpent', W_img: 'http://media.blizzard.com/heroes/li-li/abilities/icons/cloud-serpent.png',
          E_spell: 'Blinding Wind', E_img: 'http://media.blizzard.com/heroes/li-li/abilities/icons/blinding-wind.png',
          R1_spell: 'Jug of 1000 Cups', R1_img: 'http://media.blizzard.com/heroes/li-li/abilities/icons/jug-of-1000-cups.png',
          R2_spell: 'Water Dragon', R2_img: 'http://media.blizzard.com/heroes/li-li/abilities/icons/water-dragon.png',
	  R3_spell: 0, R3_img: 0},
        { id: 31, name: 'Li-Ming, Rebellious Wizard', desc: 'Assassin', life: 1232, regen: 2.57, AA:63, AS: 1.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/li-ming/skins/thumbnails/rebellious-wizard.jpg',
          trait: 'Critical Mass', trait_img: 'http://media.blizzard.com/heroes/li-ming/abilities/icons/critical-mass.png',
          Q_spell: 'Magic Missiles', Q_img: 'http://media.blizzard.com/heroes/li-ming/abilities/icons/magic-missiles.png',
          W_spell: 'Arcarne Orb', W_img: 'http://media.blizzard.com/heroes/li-ming/abilities/icons/arcane-orb.png',
          E_spell: 'Teleport', E_img: 'http://media.blizzard.com/heroes/li-ming/abilities/icons/teleport.png',
          R1_spell: 'Disintegrate', R1_img: 'http://media.blizzard.com/heroes/li-ming/abilities/icons/disintegrate.png',
          R2_spell: 'Wave of Force', R2_img: 'http://media.blizzard.com/heroes/li-ming/abilities/icons/wave-of-force.png',
	  R3_spell: 0, R3_img: 0},
        { id: 32, name: 'Lt.Morales, Combat Medic', desc: 'Support', life: 1528, regen: 3.18, AA:88, AS: 1.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/lt-morales/skins/thumbnails/combat-medic.jpg',
          trait: 'Caduceus Reactor', trait_img: 'http://media.blizzard.com/heroes/lt-morales/abilities/icons/caduceus-reactor.png',
          Q_spell: 'Healing Beam', Q_img: 'http://media.blizzard.com/heroes/lt-morales/abilities/icons/healing-beam.png',
          W_spell: 'Safeguard', W_img: 'http://media.blizzard.com/heroes/lt-morales/abilities/icons/safeguard.png',
          E_spell: 'Displacement Grenade', E_img: 'http://media.blizzard.com/heroes/lt-morales/abilities/icons/displacement-grenade.png',
          R1_spell: 'Stim Drone', R1_img: 'http://media.blizzard.com/heroes/lt-morales/abilities/icons/stim-drone.png',
          R2_spell: 'Medivac Dropship', R2_img: 'http://media.blizzard.com/heroes/lt-morales/abilities/icons/medivac-dropship.png',
	  R3_spell: 0, R3_img: 0},
        { id: 33, name: 'Lucio, Freedom Fighting DJ', desc: 'Support', life: 1380, regen: 2.88, AA:24, AS: 3.20, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/lucio/skins/thumbnails/freedom-fighting-dj.jpg',
          trait: 'Wall Ride', trait_img: 'http://media.blizzard.com/heroes/lucio/abilities/icons/wall-ride.png',
          Q_spell: 'SoundWave', Q_img: 'http://media.blizzard.com/heroes/lucio/abilities/icons/soundwave.png',
          W_spell: 'Crossfade', W_img: 'http://media.blizzard.com/heroes/lucio/abilities/icons/crossfade.png',
          E_spell: 'Amp It Up', E_img: 'http://media.blizzard.com/heroes/lucio/abilities/icons/amp-it-up.png',
          R1_spell: 'Sound Barrier', R1_img: 'http://media.blizzard.com/heroes/lucio/abilities/icons/sound-barrier.png',
          R2_spell: 'Reverse Amp', R2_img: 'http://media.blizzard.com/heroes/lucio/abilities/icons/reverse-amp.png',
	  R3_spell: 0, R3_img: 0},
        { id: 34, name: 'Lunara, First Daughter of Cenarius', desc: 'Assassin', life: 1430, regen: 2.98, AA:90, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/lunara/skins/thumbnails/first-daughter-of-cenarius.jpg',
          trait: 'Nature\'s Toxin', trait_img: 'http://media.blizzard.com/heroes/lunara/abilities/icons/natures-toxin.png',
          Q_spell: 'Noxious Blossom', Q_img: 'http://media.blizzard.com/heroes/lunara/abilities/icons/noxious-blossom.png',
          W_spell: 'Crippling Spores', W_img: 'http://media.blizzard.com/heroes/lunara/abilities/icons/crippling-spores.png',
          E_spell: 'Wisp', E_img: 'http://media.blizzard.com/heroes/lunara/abilities/icons/wisp.png',
          R1_spell: 'Thornwood Vine', R1_img: 'http://media.blizzard.com/heroes/lunara/abilities/icons/thornwood-vine.png',
          R2_spell: 'Leaping Strike', R2_img: 'http://media.blizzard.com/heroes/lunara/abilities/icons/leaping-strike.png',
	  R3_spell: 0, R3_img: 0},
        { id: 35, name: 'Malfurion, Archdruid', desc: 'Support', life: 1682, regen: 3.50, AA:67, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/malfurion/skins/thumbnails/archdruid.jpg',
          trait: 'Innervate', trait_img: 'http://media.blizzard.com/heroes/malfurion/abilities/icons/innervate.png',
          Q_spell: 'Regrowth', Q_img: 'http://media.blizzard.com/heroes/malfurion/abilities/icons/regrowth.png',
          W_spell: 'Moonfire', W_img: 'http://media.blizzard.com/heroes/malfurion/abilities/icons/moonfire.png',
          E_spell: 'Entangling Roots', E_img: 'http://media.blizzard.com/heroes/malfurion/abilities/icons/entangling-roots.png',
          R1_spell: 'Tranquility', R1_img: 'http://media.blizzard.com/heroes/malfurion/abilities/icons/tranquility.png',
          R2_spell: 'Twilight Dream', R2_img: 'http://media.blizzard.com/heroes/malfurion/abilities/icons/twilight-dream.png',
	  R3_spell: 0, R3_img: 0},
        { id: 37, name: 'Malthael, Aspect of Death', desc: 'Assassin', life: 0, regen: 0, AA:0, AS: 0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/malthael/skins/thumbnails/aspect-of-death.jpg',
          trait: 'Reaper\'s Mark', trait_img: 'http://media.blizzard.com/heroes/malthael/abilities/icons/reapers-mark.png',
          Q_spell: 'Soul Rip', Q_img: 'http://media.blizzard.com/heroes/malthael/abilities/icons/soul-rip.png',
          W_spell: 'Wraith Strike', W_img: 'http://media.blizzard.com/heroes/malthael/abilities/icons/wraith-strike.png',
          E_spell: 'Death Shroud', E_img: 'http://media.blizzard.com/heroes/malthael/abilities/icons/death-shroud.png',
          R1_spell: 'Tormented Souls', R1_img: 'http://media.blizzard.com/heroes/malthael/abilities/icons/tormented-souls.png',
          R2_spell: 'Last Rites', R2_img: 'http://media.blizzard.com/heroes/malthael/abilities/icons/last-rites.png',
	  R3_spell: 0, R3_img: 0},
	{ id: 38, name: 'Medivh, the Last Guardian', desc: 'Specialist', life: 1470, regen: 3.06, AA:80, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/medivh/skins/thumbnails/the-last-guardian.jpg',
          trait: 'Raven Form', trait_img: 'http://media.blizzard.com/heroes/medivh/abilities/icons/raven-form.png',
          Q_spell: 'Arcane Rift', Q_img: 'http://media.blizzard.com/heroes/medivh/abilities/icons/arcane-rift.png',
          W_spell: 'Force of Will', W_img: 'http://media.blizzard.com/heroes/medivh/abilities/icons/force-of-will.png',
          E_spell: 'Portal', E_img: 'http://media.blizzard.com/heroes/medivh/abilities/icons/portal.png',
          R1_spell: 'Poly Bomb', R1_img: 'http://media.blizzard.com/heroes/medivh/abilities/icons/poly-bomb.png',
          R2_spell: 'Ley Line Seal', R2_img: 'http://media.blizzard.com/heroes/medivh/abilities/icons/ley-line-seal.png',
	  R3_spell: 0, R3_img: 0},
        { id: 39, name: 'Muradin, Mountain King', desc: 'Warrior', life: 2633, regen: 5.48, AA:97, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/muradin/skins/thumbnails/mountain-king.jpg',
          trait: 'Second Wind', trait_img: 'http://media.blizzard.com/heroes/muradin/abilities/icons/second-wind.png',
          Q_spell: 'Storm Bolt', Q_img: 'http://media.blizzard.com/heroes/muradin/abilities/icons/storm-bolt.png',
          W_spell: 'Thunder Clap', W_img: 'http://media.blizzard.com/heroes/muradin/abilities/icons/thunder-clap.png',
          E_spell: 'Dwarf Toss', E_img: 'http://media.blizzard.com/heroes/muradin/abilities/icons/dwarf-toss.png',
          R1_spell: 'Avatar', R1_img: 'http://media.blizzard.com/heroes/muradin/abilities/icons/avatar.png',
          R2_spell: 'Haymaker', R2_img: 'http://media.blizzard.com/heroes/muradin/abilities/icons/haymaker.png',
	  R3_spell: 0, R3_img: 0},
        { id: 40, name: 'Murky, Baby Murloc', desc: 'Specialist', life: 730, regen: 29.2, AA:60, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/murky/skins/thumbnails/baby-murloc.jpg',
          trait: 'Spawn Egg', trait_img: 'http://media.blizzard.com/heroes/murky/abilities/icons/spawn-egg.png',
          Q_spell: 'Slime', Q_img: 'http://media.blizzard.com/heroes/murky/abilities/icons/slime.png',
          W_spell: 'Pufferfish', W_img: 'http://media.blizzard.com/heroes/murky/abilities/icons/pufferfish.png',
          E_spell: 'Safety Bubble', E_img: 'http://media.blizzard.com/heroes/murky/abilities/icons/safety-bubble.png',
          R1_spell: 'March of the Murlocs', R1_img: 'http://media.blizzard.com/heroes/murky/abilities/icons/march-of-the-murlocs.png',
          R2_spell: 'Octo-Grab', R2_img: 'http://media.blizzard.com/heroes/murky/abilities/icons/octo-grab.png',
	  R3_spell: 0, R3_img: 0},
        { id: 41, name: 'Nazeebo, Heretic Witch Doctor', desc: 'Specialist', life: 1638, regen: 3.41, AA:88, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/nazeebo/skins/thumbnails/heretic-witch-doctor.jpg',
          trait: 'Voodoo Ritual', trait_img: 'http://media.blizzard.com/heroes/nazeebo/abilities/icons/voodoo-ritual.png',
          Q_spell: 'Corpse Spiders', Q_img: 'http://media.blizzard.com/heroes/nazeebo/abilities/icons/corpse-spiders.png',
          W_spell: 'Zombie Wall', W_img: 'http://media.blizzard.com/heroes/nazeebo/abilities/icons/zombie-wall.png',
          E_spell: 'Plague of Toads', E_img: 'http://media.blizzard.com/heroes/nazeebo/abilities/icons/plague-of-toads.png',
          R1_spell: 'Gargantuan', R1_img: 'http://media.blizzard.com/heroes/nazeebo/abilities/icons/gargantuan.png',
          R2_spell: 'Ravenous Spirit', R2_img: 'http://media.blizzard.com/heroes/nazeebo/abilities/icons/ravenous-spirit.png',
	  R3_spell: 0, R3_img: 0},
        { id: 42, name: 'Nova, Dominion Ghost', desc: 'Assassin', life: 1350, regen: 2.81, AA:105, AS: 1.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/nova/skins/thumbnails/dominion-ghost.jpg',
          trait: 'Permanent Cloak, Sniper', trait_img: 'http://media.blizzard.com/heroes/nova/abilities/icons/permanent-cloak-sniper.png',
          Q_spell: 'Snipe', Q_img: 'http://media.blizzard.com/heroes/nova/abilities/icons/snipe.png',
          W_spell: 'Pinning Shot', W_img: 'http://media.blizzard.com/heroes/nova/abilities/icons/pinning-shot.png',
          E_spell: 'Holo Decoy', E_img: 'http://media.blizzard.com/heroes/nova/abilities/icons/holo-decoy.png',
          R1_spell: 'Triple Tap', R1_img: 'http://media.blizzard.com/heroes/nova/abilities/icons/triple-tap.png',
          R2_spell: 'Precision Strike', R2_img: 'http://media.blizzard.com/heroes/nova/abilities/icons/precision-strike.png',
	  R3_spell: 0, R3_img: 0},
        { id: 43, name: 'Probius, Curious Probe', desc: 'Specialist', life: 1260, regen: 2.6, AA:33, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/probius/skins/thumbnails/curious-probe.jpg',
          trait: 'Warp in Pylon', trait_img: 'http://media.blizzard.com/heroes/probius/abilities/icons/warp-in-pylon.png',
          Q_spell: 'Disruption Pulse', Q_img: 'http://media.blizzard.com/heroes/probius/abilities/icons/disruption-pulse.png',
          W_spell: 'Warp Rift', W_img: 'http://media.blizzard.com/heroes/probius/abilities/icons/warp-rift.png',
          E_spell: 'Photon Cannon', E_img: 'http://media.blizzard.com/heroes/probius/abilities/icons/photon-cannon.png',
          R1_spell: 'Pylon Overcharge', R1_img: 'http://media.blizzard.com/heroes/probius/abilities/icons/pylon-overcharge.png',
          R2_spell: 'Null Gate', R2_img: 'http://media.blizzard.com/heroes/probius/abilities/icons/null-gate.png',
	  R3_spell: 0, R3_img: 0},
        { id: 44, name: 'Ragnaros, the Firelord', desc: 'Assassin', life: 2000, regen: 4.2, AA:171, AS: 0.83, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/ragnaros/skins/thumbnails/the-firelord.jpg',
          trait: 'Molten Core', trait_img: 'http://media.blizzard.com/heroes/ragnaros/abilities/icons/molten-core.png',
          Q_spell: 'Empower Sulfuras', Q_img: 'http://media.blizzard.com/heroes/ragnaros/abilities/icons/empower-sulfuras.png',
          W_spell: 'Living Meteor', W_img: 'http://media.blizzard.com/heroes/ragnaros/abilities/icons/living-meteor.png',
          E_spell: 'Blast Wave', E_img: 'http://media.blizzard.com/heroes/ragnaros/abilities/icons/blast-wave.png',
          R1_spell: 'Sulfuras Smash', R1_img: 'http://media.blizzard.com/heroes/ragnaros/abilities/icons/sulfuras-smash.png',
          R2_spell: 'Lava Wave', R2_img: 'http://media.blizzard.com/heroes/ragnaros/abilities/icons/lava-wave.png',
	  R3_spell: 0, R3_img: 0},
        { id: 45, name: 'Raynor, Renegade Commander', desc: 'Assassin', life: 1302, regen: 2.71, AA:122, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/raynor/skins/thumbnails/renegade-commander.jpg',
          trait: 'Advanced Optics', trait_img: 'http://media.blizzard.com/heroes/raynor/abilities/icons/advanced-optics.png',
          Q_spell: 'Penetrating Round', Q_img: 'http://media.blizzard.com/heroes/raynor/abilities/icons/penetrating-round.png',
          W_spell: 'Inspire', W_img: 'http://media.blizzard.com/heroes/raynor/abilities/icons/inspire.png',
          E_spell: 'Adrenaline Rush', E_img: 'http://media.blizzard.com/heroes/raynor/abilities/icons/adrenaline-rush.png',
          R1_spell: 'Hyperion', R1_img: 'http://media.blizzard.com/heroes/raynor/abilities/icons/hyperion.png',
          R2_spell: 'Raynor\'s Raiders', R2_img: 'http://media.blizzard.com/heroes/raynor/abilities/icons/raynors-raiders.png',
	  R3_spell: 0, R3_img: 0},
        { id: 46, name: 'Rehgar, Shaman of the Earthen Ring', desc: 'Support', life: 2049, regen: 4.27, AA:120, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/rehgar/skins/thumbnails/shaman-of-the-earthen-ring.jpg',
          trait: 'Ghost Wolf', trait_img: 'http://media.blizzard.com/heroes/rehgar/abilities/icons/ghost-wolf.png',
          Q_spell: 'Chain Heal', Q_img: 'http://media.blizzard.com/heroes/rehgar/abilities/icons/chain-heal.png',
          W_spell: 'Lightning Shield', W_img: 'http://media.blizzard.com/heroes/rehgar/abilities/icons/lightning-shield.png',
          E_spell: 'Earthbind Totem', E_img: 'http://media.blizzard.com/heroes/rehgar/abilities/icons/earthbind-totem.png',
          R1_spell: 'Ancestral Healing', R1_img: 'http://media.blizzard.com/heroes/rehgar/abilities/icons/ancestral-healing.png',
          R2_spell: 'Bloodlust', R2_img: 'http://media.blizzard.com/heroes/rehgar/abilities/icons/bloodlust.png',
	  R3_spell: 0, R3_img: 0},
	{ id: 47, name: 'Rexxar, Champion of the Horde', desc: 'Warrior', life: 1725, regen: 3.59, AA:99, AS: 0.87, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/rexxar/skins/thumbnails/champion-of-the-horde.jpg',
          trait: 'Misha, Focus !', trait_img: 'http://media.blizzard.com/heroes/rexxar/abilities/icons/misha-focus.png',
          Q_spell: 'Spirit Swoop', Q_img: 'http://media.blizzard.com/heroes/rexxar/abilities/icons/spirit-swoop.png',
          W_spell: 'Misha, Charge !', W_img: 'http://media.blizzard.com/heroes/rexxar/abilities/icons/misha-charge.png',
          E_spell: 'Mend Pet', E_img: 'http://media.blizzard.com/heroes/rexxar/abilities/icons/mend-pet.png',
          R1_spell: 'Bestial Wrath', R1_img: 'http://media.blizzard.com/heroes/rexxar/abilities/icons/bestial-wrath.png',
          R2_spell: 'Unleash the Boars', R2_img: 'http://media.blizzard.com/heroes/rexxar/abilities/icons/unleash-the-boars.png',
	  R3_spell: 0, R3_img: 0},
        { id: 48, name: 'Samuro, the Blademaster', desc: 'Assassin', life: 1650, regen: 3.44, AA:88, AS: 1.67, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/samuro/skins/thumbnails/the-blademaster.jpg',
          trait: 'Advancing Strikes', trait_img: 'http://media.blizzard.com/heroes/samuro/abilities/icons/advancing-strikes.png',
          Q_spell: 'Mirror Image', Q_img: 'http://media.blizzard.com/heroes/samuro/abilities/icons/mirror-image.png',
          W_spell: 'Critical Strike', W_img: 'http://media.blizzard.com/heroes/samuro/abilities/icons/critical-strike.png',
          E_spell: 'Wind Walk', E_img: 'http://media.blizzard.com/heroes/samuro/abilities/icons/wind-walk.png',
          R1_spell: 'Bladestorm', R1_img: 'http://media.blizzard.com/heroes/samuro/abilities/icons/bladestorm.png',
          R2_spell: 'Illusion Master', R2_img: 'http://media.blizzard.com/heroes/samuro/abilities/icons/illusion-master.png',
	  R3_spell: 0, R3_img: 0},
        { id: 49, name: 'Sgt.Hammer, Siege Tank Operator', desc: 'Specialist', life: 1638, regen: 3.41, AA:128, AS: 1.00, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/sgt-hammer/skins/thumbnails/siege-tank-operator.jpg',
          trait: 'Artillery', trait_img: 'http://media.blizzard.com/heroes/sgt-hammer/abilities/icons/artillery.png',
          Q_spell: 'Spider Mines', Q_img: 'http://media.blizzard.com/heroes/sgt-hammer/abilities/icons/spider-mines.png',
          W_spell: 'Concussive Blast', W_img: 'http://media.blizzard.com/heroes/sgt-hammer/abilities/icons/concussive-blast.png',
          E_spell: 'Siege Mode', E_img: 'http://media.blizzard.com/heroes/sgt-hammer/abilities/icons/siege-mode.png',
          R1_spell: 'Blunt Force Gun', R1_img: 'http://media.blizzard.com/heroes/sgt-hammer/abilities/icons/blunt-force-gun.png',
          R2_spell: 'Napalm Strike', R2_img: 'http://media.blizzard.com/heroes/sgt-hammer/abilities/icons/napalm-strike.png',
	  R3_spell: 0, R3_img: 0},
        { id: 50, name: 'Sonya, Wandering Barbarian', desc: 'Warrior', life: 2341, regen: 4.88, AA:88, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/sonya/skins/thumbnails/wandering-barbarian.jpg',
          trait: 'Fury', trait_img: 'http://media.blizzard.com/heroes/sonya/abilities/icons/fury.png',
          Q_spell: 'Ancient Spear', Q_img: 'http://media.blizzard.com/heroes/sonya/abilities/icons/ancient-spear.png',
          W_spell: 'Seismic Slam', W_img: 'http://media.blizzard.com/heroes/sonya/abilities/icons/seismic-slam.png',
          E_spell: 'Whirlwind', E_img: 'http://media.blizzard.com/heroes/sonya/abilities/icons/whirlwind.png',
          R1_spell: 'Leap', R1_img: 'http://media.blizzard.com/heroes/sonya/abilities/icons/leap.png',
          R2_spell: 'Wrath of the Berserker', R2_img: 'http://media.blizzard.com/heroes/sonya/abilities/icons/wrath-of-the-berserker.png',
	  R3_spell: 0, R3_img: 0},
        { id: 51, name: 'Stitches, Terror of Darkshire', desc: 'Warrior', life: 3000, regen: 6.25, AA:85, AS: 0.91, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/stitches/skins/thumbnails/terror-of-darkshire.jpg',
          trait: 'Vile Gas', trait_img: 'http://media.blizzard.com/heroes/stitches/abilities/icons/vile-gas.png',
          Q_spell: 'Hook', Q_img: 'http://media.blizzard.com/heroes/stitches/abilities/icons/hook.png',
          W_spell: 'Slam', W_img: 'http://media.blizzard.com/heroes/stitches/abilities/icons/slam.png',
          E_spell: 'Devour', E_img: 'http://media.blizzard.com/heroes/stitches/abilities/icons/devour.png',
          R1_spell: 'Putrid Bile', R1_img: 'http://media.blizzard.com/heroes/stitches/abilities/icons/putrid-bile.png',
          R2_spell: 'Gorge', R2_img: 'http://media.blizzard.com/heroes/stitches/abilities/icons/gorge.png',
	  R3_spell: 0, R3_img: 0},
        { id: 52, name: 'Sylvanas, the Banshee Queen', desc: 'Sylvanas', life: 1456, regen: 3.04, AA:85, AS: 1.67, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/sylvanas/skins/thumbnails/the-banshee-queen.jpg',
          trait: 'Black Arrows', trait_img: 'http://media.blizzard.com/heroes/sylvanas/abilities/icons/black-arrows.png',
          Q_spell: 'Withering Fire', Q_img: 'http://media.blizzard.com/heroes/sylvanas/abilities/icons/withering-fire.png',
          W_spell: 'Shadow Dagger', W_img: 'http://media.blizzard.com/heroes/sylvanas/abilities/icons/shadow-dagger.png',
          E_spell: 'Haunting Wave', E_img: 'http://media.blizzard.com/heroes/sylvanas/abilities/icons/haunting-wave.png',
          R1_spell: 'Wailing Arrow', R1_img: 'http://media.blizzard.com/heroes/sylvanas/abilities/icons/wailing-arrow.png',
          R2_spell: 'Mind Control', R2_img: 'http://media.blizzard.com/heroes/sylvanas/abilities/icons/mind-control.png',
	  R3_spell: 0, R3_img: 0},
        { id: 53, name: 'Tassadar, Savior of the Templar', desc: 'Support', life: 1426, regen: 2.97, AA:15, AS: 1.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/tassadar/skins/thumbnails/savior-of-the-templar.jpg',
          trait: 'Oracle', trait_img: 'http://media.blizzard.com/heroes/tassadar/abilities/icons/oracle.png',
          Q_spell: 'Plasma Shield', Q_img: 'http://media.blizzard.com/heroes/tassadar/abilities/icons/plasma-shield.png',
          W_spell: 'Psionic Storm', W_img: 'http://media.blizzard.com/heroes/tassadar/abilities/icons/psionic-storm.png',
          E_spell: 'Dimensional Shift', E_img: 'http://media.blizzard.com/heroes/tassadar/abilities/icons/dimensional-shift.png',
          R1_spell: 'Archon', R1_img: 'http://media.blizzard.com/heroes/tassadar/abilities/icons/archon.png',
          R2_spell: 'Force Wall', R2_img: 'http://media.blizzard.com/heroes/tassadar/abilities/icons/force-wall.png',
	  R3_spell: 0, R3_img: 0},
        { id: 54, name: 'The Butcher, Flesh Carver', desc: 'Assassin', life: 2154, regen: 4.49, AA:140, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/the-butcher/skins/thumbnails/flesh-carver.jpg',
          trait: 'Fresh Meat', trait_img: 'http://media.blizzard.com/heroes/the-butcher/abilities/icons/fresh-meat.png',
          Q_spell: 'Hamstring', Q_img: 'http://media.blizzard.com/heroes/the-butcher/abilities/icons/hamstring.png',
          W_spell: 'Butcher\'s Brand', W_img: 'http://media.blizzard.com/heroes/the-butcher/abilities/icons/butchers-brand.png',
          E_spell: 'Ruthless Onslaught', E_img: 'http://media.blizzard.com/heroes/the-butcher/abilities/icons/ruthless-onslaught.png',
          R1_spell: 'Furnace Blast', R1_img: 'http://media.blizzard.com/heroes/the-butcher/abilities/icons/furnace-blast.png',
          R2_spell: 'Lamb to the Slaughter', R2_img: 'http://media.blizzard.com/heroes/the-butcher/abilities/icons/lamb-to-the-slaughter.png',
	  R3_spell: 0, R3_img: 0},
        { id: 55, name: 'The Lost Vikings, Triple Trouble', desc: 'Specialist', life: 0, regen: 0, AA:0, AS: 0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA:0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/the-lost-vikings/skins/thumbnails/triple-trouble.jpg',
          trait: 'Viking Hoard', trait_img: 'http://media.blizzard.com/heroes/the-lost-vikings/abilities/icons/viking-hoard.png',
          Q_spell: 'Pick your Spell', Q_img: 'http://media.blizzard.com/heroes/kharazim/abilities/icons/pick-your-trait.png',
          W_spell: 'Pick your Spell', W_img: 'http://media.blizzard.com/heroes/kharazim/abilities/icons/pick-your-trait.png',
          E_spell: 'Pick your Spell', E_img: 'http://media.blizzard.com/heroes/kharazim/abilities/icons/pick-your-trait.png',
          R1_spell: 'Longboat Raid!', R1_img: 'http://media.blizzard.com/heroes/the-lost-vikings/abilities/icons/longboat-raid.png',
          R2_spell: 'Play Again!', R2_img: 'http://media.blizzard.com/heroes/the-lost-vikings/abilities/icons/play-again.png',
	  R3_spell: 0, R3_img: 0},
	{ id: 56, name: 'Thrall, Warlord of the Horder', desc: 'Assassin', life: 1787, regen: 3.72, AA:165, AS: 0.91, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/thrall/skins/thumbnails/warchief-of-the-horde.jpg',
          trait: 'Frostwolf Resilience', trait_img: 'http://media.blizzard.com/heroes/thrall/abilities/icons/frostwolf-resilience.png',
          Q_spell: 'Chain Lightning', Q_img: 'http://media.blizzard.com/heroes/thrall/abilities/icons/chain-lightning.png',
          W_spell: 'Feral Spirit', W_img: 'http://media.blizzard.com/heroes/thrall/abilities/icons/feral-spirit.png',
          E_spell: 'Windfury', E_img: 'http://media.blizzard.com/heroes/thrall/abilities/icons/windfury.png',
          R1_spell: 'Sundering', R1_img: 'http://media.blizzard.com/heroes/thrall/abilities/icons/sundering.png',
          R2_spell: 'Earthquake', R2_img: 'http://media.blizzard.com/heroes/thrall/abilities/icons/earthquake.png',
	  R3_spell: 0, R3_img: 0},
        { id: 57, name: 'Tracer, Agent of Overwatch', desc: 'Assassin', life: 1206, regen: 5.02, AA:27, AS: 8.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/tracer/skins/thumbnails/agent-of-overwatch.jpg',
          trait: 'Reload', trait_img: 'http://media.blizzard.com/heroes/tracer/abilities/icons/reload.png',
          Q_spell: 'Blink', Q_img: 'http://media.blizzard.com/heroes/tracer/abilities/icons/blink.png',
          W_spell: 'Melee', W_img: 'http://media.blizzard.com/heroes/tracer/abilities/icons/melee.png',
          E_spell: 'Recall', E_img: 'http://media.blizzard.com/heroes/tracer/abilities/icons/recall.png',
          R1_spell: 'Pulse Bomb', R1_img: 'http://media.blizzard.com/heroes/tracer/abilities/icons/pulse-bomb.png',
          R2_spell: 0, R2_img: 0,
	  R3_spell: 0, R3_img: 0 },
        { id: 58, name: 'Tychus, Notorious Outlaw', desc: 'Assassin', life: 1925, regen: 4.01, AA:44, AS: 4.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/tychus/skins/thumbnails/notorious-outlaw.jpg',
          trait: 'Minigun', trait_img: 'http://media.blizzard.com/heroes/tychus/abilities/icons/minigun.png',
          Q_spell: 'Overkill', Q_img: 'http://media.blizzard.com/heroes/tychus/abilities/icons/overkill.png',
          W_spell: 'Frag Grenade', W_img: 'http://media.blizzard.com/heroes/tychus/abilities/icons/frag-grenade.png',
          E_spell: 'Run and Gun', E_img: 'http://media.blizzard.com/heroes/tychus/abilities/icons/run-and-gun.png',
          R1_spell: 'Commandeer Odin', R1_img: 'http://media.blizzard.com/heroes/tychus/abilities/icons/commandeer-odin.png',
          R2_spell: 'Drakken Laser Drill', R2_img: 'http://media.blizzard.com/heroes/tychus/abilities/icons/drakken-laser-drill.png',
	  R3_spell: 0, R3_img: 0},
        { id: 59, name: 'Tyrael, Archangel of Justice', desc: 'Warrior', life: 2296, regen: 4.78, AA:78, AS: 1.25, armor: 0, Parmor: 0, Marmor: 15, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/tyrael/skins/thumbnails/archangel-of-justice.jpg',
          trait: 'Archangel\'s Wrath', trait_img: 'http://media.blizzard.com/heroes/tyrael/abilities/icons/archangels-wrath.png',
          Q_spell: 'El\'Druin\'s Might', Q_img: 'http://media.blizzard.com/heroes/tyrael/abilities/icons/eldruins-might.png',
          W_spell: 'Righteousness', W_img: 'http://media.blizzard.com/heroes/tyrael/abilities/icons/righteousness.png',
          E_spell: 'Smite', E_img: 'http://media.blizzard.com/heroes/tyrael/abilities/icons/smite.png',
          R1_spell: 'Judgment', R1_img: 'http://media.blizzard.com/heroes/tyrael/abilities/icons/judgment.png',
          R2_spell: 'Sanctification', R2_img: 'http://media.blizzard.com/heroes/tyrael/abilities/icons/sanctification.png',
	  R3_spell: 0, R3_img: 0},
        { id: 60, name: 'Tyrande, High Prietess of Elune', desc: 'Support', life: 1591, regen: 3.32, AA:87, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/tyrande/skins/thumbnails/high-priestess-of-elune.jpg',
          trait: 'Hunter\'s Mark', trait_img: 'http://media.blizzard.com/heroes/tyrande/abilities/icons/hunters-mark.png',
          Q_spell: 'Light of Elune', Q_img: 'http://media.blizzard.com/heroes/tyrande/abilities/icons/light-of-elune.png',
          W_spell: 'Sentinel', W_img: 'http://media.blizzard.com/heroes/tyrande/abilities/icons/sentinel.png',
          E_spell: 'Lunar Flare', E_img: 'http://media.blizzard.com/heroes/tyrande/abilities/icons/lunar-flare.png',
          R1_spell: 'Shadowstalk', R1_img: 'http://media.blizzard.com/heroes/tyrande/abilities/icons/shadowstalk.png',
          R2_spell: 'Starfall', R2_img: 'http://media.blizzard.com/heroes/tyrande/abilities/icons/starfall.png',
	  R3_spell: 0, R3_img: 0},
        { id: 61, name: 'Uther, the Lightbringer', desc: 'Support', life: 2156, regen: 4.49, AA:78, AS: 1.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA:0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/uther/skins/thumbnails/the-lightbringer.jpg',
          trait: 'Devotion, Eternal Vanguard', trait_img: 'http://media.blizzard.com/heroes/uther/abilities/icons/devotion-eternal-vanguard.png',
          Q_spell: 'Holy Light', Q_img: 'http://media.blizzard.com/heroes/uther/abilities/icons/holy-light.png',
          W_spell: 'Holy Radiance', W_img: 'http://media.blizzard.com/heroes/uther/abilities/icons/holy-radiance.png',
          E_spell: 'Hammer of Justice', E_img: 'http://media.blizzard.com/heroes/uther/abilities/icons/hammer-of-justice.png',
          R1_spell: 'Divine Shield', R1_img: 'http://media.blizzard.com/heroes/uther/abilities/icons/divine-shield.png',
          R2_spell: 'Divine Storm', R2_img: 'http://media.blizzard.com/heroes/uther/abilities/icons/divine-storm.png',
	  R3_spell: 0, R3_img: 0},
        { id: 62, name: 'Valeera, Shadow of the Uncrowned', desc: 'Assassin', life: 2047, regen: 4.26, AA:79, AS: 2.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/valeera/skins/thumbnails/standard/shadow-of-the-uncrowned.jpg',
          trait: 'Vanish', trait_img: 'http://media.blizzard.com/heroes/valeera/abilities/icons/standard/vanish.png',
          Q_spell: 'Sinister Strike', Q_img: 'http://media.blizzard.com/heroes/valeera/abilities/icons/standard/sinister-strike.png',
          W_spell: 'Blade Flurry', W_img: 'http://media.blizzard.com/heroes/valeera/abilities/icons/standard/blade-flurry.png',
          E_spell: 'Eviscerate', E_img: 'http://media.blizzard.com/heroes/valeera/abilities/icons/standard/eviscerate.png',
          R1_spell: 'Smoke Bomb', R1_img: 'http://media.blizzard.com/heroes/valeera/abilities/icons/standard/smoke-bomb.png',
          R2_spell: 'Cloak of Shadows', R2_img: 'http://media.blizzard.com/heroes/valeera/abilities/icons/standard/cloak-of-shadows.png',
	  R3_spell: 0, R3_img: 0},
        { id: 63, name: 'Valla, Demon Hunter', desc: 'Assassin', life: 1273, regen: 2.65, AA:75, AS: 1.67, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/valla/skins/thumbnails/demon-hunter.jpg',
          trait: 'Hatred, Basic Attack grant a stack of Hatred, up to 10.Each Hatred stack increases Basic Attack damage by 8% and Movement Speed by 1%.Last 4 seconds', 
	  trait_img: 'http://media.blizzard.com/heroes/valla/abilities/icons/hatred.png',
          Q_spell: 'Hungering Arrow, Fire an Arrow that deals 146 (+4% per level) damage to the first target hit, then seek up to 2 additional enemies dealing 84 (+4% per level) damage.Can hit an enemy multiple times.',
	  Q_img: 'http://media.blizzard.com/heroes/valla/abilities/icons/hungering-arrow.png',
          W_spell: 'Multishot, Deal 171 damage to enemies within the target area',
	  W_img: 'http://media.blizzard.com/heroes/valla/abilities/icons/multishot.png',
          E_spell: 'Vault, dash to the target area. Your next Basic Attack within 2 seconds deals 5% increased damage per stack of Hatred.',
	  E_img: 'http://media.blizzard.com/heroes/valla/abilities/icons/vault.png',
          R1_spell: 'Strafe, Rapidly attack nearby visible enemis for 60 (+4% per level) damage per hit, prioritizing heroes over minion. Valla is able to move and Vault while strafing.Lasts for 4 seconds',
	  R1_img: 'http://media.blizzard.com/heroes/valla/abilities/icons/strafe.png',
          R2_spell: 'Rain of Vengeance, Launch a wave of Shadow Beasts that deals 250 (+4% per level) damage and stuns enemies in the target area for 0.5 second.Stores 2 charges.',
	  R2_img: 'http://media.blizzard.com/heroes/valla/abilities/icons/rain-of-vengeance.png',
	  R3_spell: 0, R3_img: 0},
        { id: 64, name: 'Varian, High King of the Alliance', desc: 'Multiclass: Assasin/Warrior', life: 2322, regen: 4.84, AA:91, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 0, scaleA: 3.5, scaleH: 3.0,
	  icone_img: 'http://media.blizzard.com/heroes/varian/skins/thumbnails/warrior/high-king-of-the-alliance.jpg',
          trait: 'Heroic Strike', trait_img: 'http://media.blizzard.com/heroes/varian/abilities/icons/warrior/heroic-strike.png',
          Q_spell: 'Lion\' Fang', Q_img: 'http://media.blizzard.com/heroes/varian/abilities/icons/warrior/lions-fang.png',
          W_spell: 'Parry', W_img: 'http://media.blizzard.com/heroes/varian/abilities/icons/warrior/parry.png',
          E_spell: 'Charge', E_img: 'http://media.blizzard.com/heroes/varian/abilities/icons/warrior/charge.png',
          R1_spell: 'Taunt', R1_img: 'http://media.blizzard.com/heroes/varian/abilities/icons/warrior/taunt.png',
          R2_spell: 'Colossus Smash', R2_img: 'http://media.blizzard.com/heroes/varian/abilities/icons/assassin/colossus-smash.png',
	  R3_spell: 'Twin Blades of Fury', R3_img: 'http://media.blizzard.com/heroes/varian/abilities/icons/assassin/twin-blades-of-fury.png' },
	{ id: 65, name: 'Xul, Cryptic Necromancer', desc: 'Specialist', life: 1900, regen: 3.96, AA:104, AS: 1.20, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/xul/skins/thumbnails/cryptic-necromancer.jpg',
          trait: 'Raise Skeleton', trait_img: 'http://media.blizzard.com/heroes/xul/abilities/icons/raise-skeleton.png',
          Q_spell: 'Spectral Scythe', Q_img: 'http://media.blizzard.com/heroes/xul/abilities/icons/spectral-scythe.png',
          W_spell: 'Cursed Strikes', W_img: 'http://media.blizzard.com/heroes/xul/abilities/icons/cursed-strikes.png',
          E_spell: 'Bone Prison', E_img: 'http://media.blizzard.com/heroes/xul/abilities/icons/bone-prison.png',
          R1_spell: 'Poison Nova', R1_img: 'http://media.blizzard.com/heroes/xul/abilities/icons/poison-nova.png',
          R2_spell: 'Skeletal Mages', R2_img: 'http://media.blizzard.com/heroes/xul/abilities/icons/skeletal-mages.png',
	  R3_spell: 0, R3_img: 0},
        { id: 66, name: 'Zagara, Broodmother of the Swarm', desc: 'Specialist', life: 1643, regen: 3.42, AA:82, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/zagara/skins/thumbnails/broodmother-of-the-swarm.jpg',
          trait: 'Creep Tumor', trait_img: 'http://media.blizzard.com/heroes/zagara/abilities/icons/creep-tumor.png',
          Q_spell: 'Baneling Barrage', Q_img: 'http://media.blizzard.com/heroes/zagara/abilities/icons/baneling-barrage.png',
          W_spell: 'Hunter Killer', W_img: 'http://media.blizzard.com/heroes/zagara/abilities/icons/hunter-killer.png',
          E_spell: 'Infested Drop', E_img: 'http://media.blizzard.com/heroes/zagara/abilities/icons/infested-drop.png',
          R1_spell: 'Devoring Maw', R1_img: 'http://media.blizzard.com/heroes/zagara/abilities/icons/devouring-maw.png',
          R2_spell: 'Nydus Network', R2_img: 'http://media.blizzard.com/heroes/zagara/abilities/icons/nydus-network.png',
	  R3_spell: 0, R3_img: 0},
        { id: 67, name: 'Zarya, Defender of Russia', desc: 'Warrior', life: 2225, regen: 4.64, AA:20, AS: 4.0, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/zarya/skins/thumbnails/defender-of-russia.jpg',
          trait: 'Energy', trait_img: 'http://media.blizzard.com/heroes/zarya/abilities/icons/energy.png',
          Q_spell: 'Particle Grenade', Q_img: 'http://media.blizzard.com/heroes/zarya/abilities/icons/particle-grenade.png',
          W_spell: 'Personal Barrier', W_img: 'http://media.blizzard.com/heroes/zarya/abilities/icons/personal-barrier.png',
          E_spell: 'Shield Ally', E_img: 'http://media.blizzard.com/heroes/zarya/abilities/icons/shield-ally.png',
          R1_spell: 'Graviton Surge', R1_img: 'http://media.blizzard.com/heroes/zarya/abilities/icons/graviton-surge.png',
          R2_spell: 'Expulsion Zone', R2_img: 'http://media.blizzard.com/heroes/zarya/abilities/icons/expulsion-zone.png',
	  R3_spell: 0, R3_img: 0},
        { id: 68, name: 'Zeratul, Dark Prelate', desc: 'Assassin', life: 1622, regen: 3.38, AA:126, AS: 1.11, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/zeratul/skins/thumbnails/dark-prelate.jpg',
          trait: 'Permanent Cloak', trait_img: 'http://media.blizzard.com/heroes/zeratul/abilities/icons/permanent-cloak.png',
          Q_spell: 'Cleave', Q_img: 'http://media.blizzard.com/heroes/zeratul/abilities/icons/cleave.png',
          W_spell: 'Singularity Spike', W_img: 'http://media.blizzard.com/heroes/zeratul/abilities/icons/singularity-spike.png',
          E_spell: 'Blink', E_img: 'http://media.blizzard.com/heroes/zeratul/abilities/icons/blink.png',
          R1_spell: 'Shadow Assault', R1_img: 'http://media.blizzard.com/heroes/zeratul/abilities/icons/shadow-assault.png',
          R2_spell: 'Void Prison', R2_img: 'http://media.blizzard.com/heroes/zeratul/abilities/icons/void-prison.png',
	  R3_spell: 0, R3_img: 0},
        { id: 69, name: 'Zul\'jin, Warlord of the Amani', desc: 'Assassin', life: 1875, regen: 5.32, AA:106, AS: 1.25, armor: 0, Parmor: 0, Marmor: 0, scale: 4.0, scaleA: 0, scaleH: 0,
	  icone_img: 'http://media.blizzard.com/heroes/zuljin/skins/thumbnails/warlord-of-the-amani.jpg',
          trait: 'Berserker', trait_img: 'http://media.blizzard.com/heroes/zuljin/abilities/icons/berserker.png',
          Q_spell: 'Grievous Throw', Q_img: 'http://media.blizzard.com/heroes/zuljin/abilities/icons/grievous-throw.png',
          W_spell: 'Twin Cleave', W_img: 'http://media.blizzard.com/heroes/zuljin/abilities/icons/twin-cleave.png',
          E_spell: 'Regeneration', E_img: 'http://media.blizzard.com/heroes/zuljin/abilities/icons/regeneration.png',
          R1_spell: 'Taz\'dingo!', R1_img: 'http://media.blizzard.com/heroes/zuljin/abilities/icons/tazdingo.png',
          R2_spell: 'Guillotine', R2_img: 'http://media.blizzard.com/heroes/zuljin/abilities/icons/guillotine.png',
	  R3_spell: 0, R3_img: 0}
    ];
  return {heroes};
  };
}